""" Shared path names"""

SCIPION_WORK_DIRNAME = "/var/scipion/"
TO_DEPLOY_DIRNAME = SCIPION_WORK_DIRNAME + "to_deploy/"
DEPLOYING_DIRNAME = SCIPION_WORK_DIRNAME + "deploying/"
DEPLOYED_DIRNAME = SCIPION_WORK_DIRNAME + "deployed/"
TO_DELETE_DIRNAME = SCIPION_WORK_DIRNAME + "to_delete/"
DELETING_DIRNAME = SCIPION_WORK_DIRNAME + "deleting/"
DELETED_DIRNAME = SCIPION_WORK_DIRNAME + "deleted/"

WORK_DIRNAME = SCIPION_WORK_DIRNAME + "workdir/"

DATABASE_FILENAME = SCIPION_WORK_DIRNAME + 'deployments.json'
DEPLOY_LOG_FILENAME = SCIPION_WORK_DIRNAME + 'deploy.log'
UN_DEPLOY_LOG_FILENAME = SCIPION_WORK_DIRNAME + 'un_deploy.log'
FLAVOURS_FILENAME = SCIPION_WORK_DIRNAME + 'flavors.json'
IMAGES_FILENAME = SCIPION_WORK_DIRNAME + 'images.json'
