
- name: Deploy backend directory
  hosts: api-dev.scipion
  become: "true"

  vars_files:
    - vars/vars.yml

  tasks:

  - name: Install m4 package
    apt:
      name:             m4
      state:            present
      update_cache:     yes
      cache_valid_time: 3600

  - name: Create be-group group
    group:
      name: "{{ be_group }}"
      state: present

  - name: Create Backend user
    user:
      name: "{{ be_user }}"
      comment: "Backend user"
      state: present
      groups: "{{ be_group }}"
      shell: /bin/bash

  - name: Add www-data user to be_group
    user:
      name: www-data
      groups: "{{ be_group }}"
      append: yes

  - name: Add Backend user to sudo
    template:
      src: "backend-user.j2"
      dest: "/etc/sudoers.d/backend-user"

  - name: Create directory cfy_wrapper_dir
    file:
      path: "{{ cfy_wrapper_dir }}"
      state: directory
      mode: 0775
      owner: "{{be_user}}"
      group: "{{be_group}}"

  - name: Create directories under cfy_wrapper_dir
    file:
      path: "{{item}}"
      state: directory
      mode: 0775
      owner: "{{be_user}}"
      group: "{{be_group}}"
    with_items:
      - "{{ template_dir }}"
      - "{{ deployments_dir }}"
      - "{{ undeployed_dir }}"
      - "{{ log_dir }}"
      - "{{ scripts_dir }}"

  - name: Copy backend dir
    copy:
      src: "{{ be_src_dir }}{{ item }}"
      dest: "{{ scripts_dir }}"
      owner: "{{be_user}}"
      group: "{{be_group}}"
      mode: 0774
    with_items:
      - deploy_scipion.py
      - b_constants.py
      - get_resources.py
      - undeploy_scipion.py
      - init_templates.py
      - init_example_data.py

  - name: Copy and template bash scripts
    template:
      src: "{{ item.src }}"
      dest: "{{item.dest}}"
      owner: "{{be_user}}"
      group: "{{be_group}}"
      mode: 0774
    with_items:
      - {src: "{{ be_src_dir }}renew_proxy.j2",dest: "{{ scripts_dir }}renew_proxy.sh"}
      - {src: "{{ be_src_dir }}deploy_scipion.j2",dest: "{{ scripts_dir }}deploy_scipion.sh"}
      - {src: "{{ be_src_dir }}undeploy_scipion.j2",dest: "{{ scripts_dir }}undeploy_scipion.sh"}

#  - name: Clone repository to template dir
#    git:
#      repo: "https://github.com/ICS-MU/westlife-cloudify-scipion"
#      dest: "{{ template_dir }}"
#      depth: 1
#      version: "HEAD"


  - name: Deploy cron job
    cron:
      minute: "*/5"
      name: "Scipion deploy cron job"
      cron_file: "scipion-deploy"
      user: "{{be_user}}"
      job: "{{ scripts_dir }}deploy_scipion.py >> {{ log_dir }}deploy.log 2>&1"

  - name: Undeploy cron job
    cron:
      minute: "*/5"
      name: "Scipion undeploy cron job"
      cron_file: "scipion-undeploy"
      user: "{{be_user}}"
      job: "{{ scripts_dir }}undeploy_scipion.py >> {{ log_dir }}un_deploy.log 2>&1"

  - name: Renew proxy cron job
    cron:
      minute: "1"
      hour: "1,5,9,13,17,21"
      name: "Renew proxy"
      cron_file: "scipion-renew-proxy"
      user: "{{be_user}}"
      job: "{{ scripts_dir }}renew_proxy.sh  >> {{ log_dir }}renew.log 2>&1"
